### ISSUE TITLE
Serial port data containing invalid utf8 bytes

### ISSUE THREAD

**Issue by AureliusSlawinski** [Superwaitsum/GDSercomm#1]
I have a device which sends data over serial port, but this data is not formated as string.
It just sends bytes and I have to get my values from these bytes.

For example, the device sends me bytes like this:
165 0 21 24 11
165 0 22 22 10

In godot I get errors in the console output, because the bytes are outside of unicode range:
"unicode error: invalid skip"
"unicode error: no space left"
"unicode error: invalid utf8"

Would it be possible to have a function "readByteArray", so that the bytes from the serial port are returned as array, like [165, 0, 21, 24, 11], insted of strings?

**Comment by Superwaitsum** [comment]
Hello, sorry for the late reply.
Can you tell me your OS version? (In case it's a godot bug)
I will try to reproduce and give an appropiate fix (or a new function) for the next week.
The readByteArray function could be done with gdscript, not sure if it's needed in c++.

**Comment by AureliusSlawinski** [comment]
Great to hear.
I am on Windows 10.
This is some real data from my device (byte values, 8 bytes):
163 91 8 33 109 4  1 152
163 91 8 33 44 4  1 87
163 91 8 33 1 4  1 44

**Comment by Superwaitsum** [comment]
I couldn't test it with the values you gave me due to my mbed board giving me odd numbers when using raw values, but I added an argument to the read() function to be able to read raw values. Now using read(true) or read(1) will avoid the utf transformation and return an integer instead of a string. Please test and report if it worked for you.

**Comment by AureliusSlawinski** [comment]
I have tested the new code, and it works for me now!
Thank you very much.
The only thing I have to mention:
Values from PORT.read(1) are coming as signed integers (instead of unsigned int).
So I get values like this:
-93, 91, 8
Instead of this:
163, 91, 8

I can translate the values this way:
If value is less than 0, just do 256 + value...
```
var iDataLen = PORT.get_available()
if iDataLen>0:
	var aData = []
	var iData
	for i in range(PORT.get_available()):
		iData = PORT.read(1)
		if(iData<0):
			aData.push_back(256+iData)
		else:
			aData.push_back(iData)
```

**Comment by Superwaitsum** [comment]
Glad it worked for you. 
Interestingly the unsigned bug should not be happening since I'm using a 32 bit int to store the char. 
I will try using unsigned chars (since maybe is happening due to the compiler) or in worst case, I will just fix it using your 256 - value trick. Will commit later this week, hope you can test it then.

**Comment by AureliusSlawinski** [comment]
Sure, I will test it.
I don't know if it realy is a bug.
You are using 'char c' and not 'unsigned char c' to read from the serial port.
Maybe you could use (unsigned int)c to pass to godot, like using the uint32_t chango = c for utf8 at windows.
Btw., it was 256 + value, I corrected myself.

**Comment by Superwaitsum** [comment]
Updated with unsigned char support, finally achieved testing it (Had to use putc instead of printf on my mbed board). Hope it works for you.

**Comment by AureliusSlawinski** [comment]
I can confirm its working now with unsigned char. Thank you very much.
